name = "jj100-be"
main = "src/index.ts"
compatibility_date = "2025-04-01"
usage_model = "unbound"

[vars]
SUPABASE_URL = "https://vchoisaglmnjyhiieete.supabase.co"
SUPABASE_ANON_KEY = "your-public-anon-key"
CURRENT_COMPETITION_ID = "3527246"

[observability.logs]
enabled = true

[triggers]
crons = ["0 * * * *", "*/5 * * * *"]